version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cinema-db
    command: ['--port=5001']
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_pass
      MYSQL_ROOT_PASSWORD: masha2005
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
    ports:
      - "5001:5001"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: cinema-backend
    ports:
      - "5012:5012"
    environment:
      - PORT=5012
      - DB_HOST=db
      - DB_PORT=5001
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: cinema-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://backend:5012/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge