version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cinema-db
    environment:
      MYSQL_DATABASE: cinema
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: cinema_pass
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: cinema-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:5000/api
    container_name: cinema-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge